### PR TITLE
Added explore prevalence with stratas

### PR DESCRIPTION
**Pull request by wivern**
Added explore prevalence with stratas as part of #1078

### CODE REVIEW

**Comment by pavgra** [comment]
1. Open Explore:

image

1. Go to Ancestor

image

1. Go to Descendant (so equal to go back)

image

Breadcrumb is still in place

**Comment by pavgra** [comment]
@chrisknoll , I do think that such check could be easily achieved by comparison of concept ID used to open the explore window and the current concept ID

**Comment by chrisknoll** [comment]
Maybe i'm missing something about 'explore':  is explore used to limit the results to just those items that are in the ancestor/descendant chain of the selected concept?  In the original feature extraction functionality, you would start by looking across all features, and if you wanted to filter directly to a hierarchy chain, you click 'explore'.  When you are done with that narrow view, you click on the X to go back to all results.  

My question is: if you click on the original concept again to explore, does that really mean you want to cancel?

**Comment by chrisknoll** [comment]
I'd appreciate it if we waited to merge these things until questions were completely addressed.

**Comment by pavgra** [comment]
> is explore used to limit the results to just those items that are in the ancestor/descendant chain of the selected concept

yes

> In the original feature extraction functionality, you would start by looking across all features, and if you wanted to filter directly to a hierarchy chain, you click 'explore'. When you are done with that narrow view, you click on the X to go back to all results.

Don't think that anything changed. Our goal was just to return back the lost functionality

**Comment by chrisknoll** [comment]
> Don't think that anything changed. Our goal was just to return back the lost functionality\

Good, so if we go by the original functionality:

Clicking explore on any feature limits results to those features to the hiearchy.
You can click explore again to go higher or lower into a hiearchy but still limit the features to those in the explored hiearchy.
Clicking back to explore the original concept _did not_ clear the explore mode.  If you wanted to return to 'all results' you would clear the selection in the top (the breadcrumb).

**Comment by pavgra** [comment]
I believe the easiest way would be to pull master down and try it out, honestly. Here we have popup, so the initial screen is for ascendants / descendants of a concept picked from report-level prevalence table. Therefore, when you open popup, there is no breadcrumbs initially

**Pull request merged**
