### PR TITLE
Estimation specification for multiple outcomes

### PR DESCRIPTION
**Pull request by anthonysena**
These are the front-end changes that need to be tested in tandem with OHDSI/WebAPI#250. These changes are related to OHDSI/WebAPI#236 and OHDSI/WebAPI#217 which allow for estimation specifications with multiple T/C pairs, multiple Os and analyses. 

This PR does not completely satisfy the requirements of OHDSI/WebAPI#236 so I plan to contribute additional commits to this branch before we merge into master. This is here to publish what has been done so far and solicit feedback.

### CODE REVIEW

**Comment by anthonysena** [comment]
Hey @chrisknoll - I've got a few more changes to push into this branch so I'll do my best to clean up any formatting differences. That said, this set of changes breaks apart the estimation specification editor into multiple sub-components so that is likely why you see so many lines added/removed.

**Comment by chrisknoll** [comment]
Ok, good to know, thanks @anthonysena. I'll keep an eye out.

**Comment by fdefalco** [comment]
After reviewing your PR it appears that most of this is in fact meaningful changes.  I'll wait for the rest of your changes and review again when you commit.  Thanks for all the great work!

**Comment by anthonysena** [comment]
I'm going to close out this PR and remove the branch as this set of changes will need a bit more time. I'm planning to put in another PR which will be focused on the estimation R-code only. Thanks!

**Pull request closed without merging**
