### PR TITLE
Various issues fixed

### PR DESCRIPTION
**Pull request by anthonysena**
This PR addresses a number of bugs as described in each commit message. Specifically:

#1200 - User bar permission warning
#1201 - Remove circular dependency for const.js
#1202 - Concept Set will not load
#1205 - Cohort generation polling
#1206 - Dispose of cohort warning subscription

Also, there is a commit for fixes related to negative controls which I did not log but am happy to do that if needed.

### CODE REVIEW

**Comment by chrisknoll** [comment]
> Also, there is a commit for fixes related to negative controls which I did not log but am happy to do that if needed.

Hi, @anthonysena, could you just summarize what should be checked for the fix for negative controls?

**Comment by anthonysena** [comment]
Sure - looking at https://github.com/OHDSI/Atlas/pull/1208/commits/6e7501acf27057d06808d9612bfa2b42df494508, there were two changes I needed to make:

1. At some point, the JobDetailsService was replaced by the jobDetail class in `js/components/evidence/components/negative-controls.js` which caused the job polling to fail. This has been changed back and is functional.
2. `js/services/CDMResultsAPI.js` was refactored to remove some redundancy but the arguments passed into the `getConceptRecordCount` function were not being passed properly to the `getConceptRecordCountWithResultsUrl` function which created a bug when you want to toggle record counts between data sources in the candidate negative controls results grid.

Hope this helps!

**Comment by chrisknoll** [comment]
@anthonysena : I am seeing the userbar warning once on startup, tho navigating to the cohort definitions does not seem to produce additional warnings.  Is the fix to completely eliminate the message, or is the message about permissions valid if it only appears once?

image

**Comment by anthonysena** [comment]
Thanks @chrisknoll for the review! To answer your question: the change I made related to the permission warning was to only show it a single time whereas the code was writing the warning out to the console for each poll to the server thus repeating the same warning over and over.

**Pull request merged**
