### PR TITLE
fix js errors for removing jnj-chart

### PR DESCRIPTION
**Pull request by chen-regen**
@anthonysena  Hi Anthony, please review this. Thank you!

### CODE REVIEW

**Comment by chrisknoll** [comment]
Hey, @chen-regen , I'm sorry this was missed, when we did the atlaschart swap, the entropy functionality was new and I didn't have a test case around it.  Thanks for the fix!

**Comment by chen-regen** [comment]
Hi @chrisknoll , no problem. Thank you for merging them in!

**Comment by chen-regen** [comment]
Hi @chrisknoll , I have a question about new atlascharts. The tooltips for entropy line chart are only showing integers now. It cuts off digits after decimal point. Is there a setting to let tooltip show all the digits after decimal point?

**Comment by chen-regen** [comment]
@chrisknoll , never mind, I got it. It's still "yFormat". Thanks.

**Comment by chrisknoll** [comment]
@chen-regen , in future, could you use rebase and mege (if the commits can go in as-is) or squash and merge (if you would like to take all the commits and make a single commit out of it).  You'd use squash when you have little fixup commits made to your PR that you don't need to see as individual commits when they get pushed into master.

Thank you!

**Pull request merged**
