### PR TITLE
Have the Clear Server Cache button clear the cdm_cache and achilles_cache tables

### PR DESCRIPTION
**Pull request by amarsan**
closes https://github.com/OHDSI/Atlas/issues/2847

Companion PR is https://github.com/OHDSI/WebAPI/pull/2406

I added an .editorconfig file so that this project can have its own style conventions. I noticed that there were mixed spaces/tabs and tab sizes within individual files. I recommend turning whitespace diffs off when reviewing this PR.

There was an existing Clear Server Cache button. I have it pointing now to the new webapi/cdmResults/clearCache endpoint. I fixed the code so that if the clearCache operation returns an error response we alert the user.

### CODE REVIEW

**Comment by chrisknoll** [comment]
The button doesn't seem to reset it's state after clicking:

image


Should it go back to the blue state after the call is complete, or is it intended to be red after?

**Comment by amarsan** [comment]
@chrisknoll I did not work on that button. I only worked on the "Clear Server Cache" button that is below the table.

**Comment by amarsan** [comment]
That "Refresh Cache" button calls that code that "warms" the cache. The warming is done in an async job.

**Comment by chrisknoll** [comment]
Ok, sorry. I misunderstood. It hought the individual buttons called the clear cache by source, and you made the bottom one do the same thing for each source.

Ok, can I ask that the buttons next to the source do the following:

1. Call the delete cache results in the WebAPI db for the given source (sync operation)
2. Call warm cache (the existing functionality).

I think we want to be able to isolate the clear cache of the individual sources...usually you have mutliple cdms set up and you only want to refresh the cache on one of them at a time.

**Comment by amarsan** [comment]
@chrisknoll Just to clarify...you'd like for the "Refresh Cache" buttons in the source table to both delete cache results and warm the cache. Did I understand that correctly?

**Comment by chrisknoll** [comment]
Makes sense: in my DEV env, I disabled all warming caches because I'm launching and relaunching all the time. so I turn that off, but I do want to be able to clear the cache, so making the button do it and then try to warm cache (but reject because it's disabled)  is a good behavior.

**Review by chrisknoll — APPROVED** [review]

**Pull request merged**
