### PR TITLE
UI improvements for CC + returned back Concept Explore feature

### LINKED ISSUE #1078: UI improvements for CC
1. Add facets to filter by Domain in Feature analyses list and Feature analyses popup
1. Allow picking multiple Feature Analyses from Feature analyses popup inside CC page (inc. select all filtered)
1. Add filtering by analysis domain into CC results page
1. Return back "Explore" button for concepts presented in CC results (like it was before in Generate w/ features)
image

@chrisknoll , I remember we had some more (not speaking here about Generations tab) but was not able to find the comment which you or @pbr6cornell posted after our call

### PR DESCRIPTION
**Pull request by wivern**
closes #1078

### CODE REVIEW

**Comment by pavgra** [comment]
@wivern , recently there were updates to dirtyFlag caused by performance issues. From now, the flag is reacting to observables changes only. Thefeore, we need to update handling of design and make it similar to Pathways approach. Currently, it is impossible to create new / update design - button is always disabled.

**Comment by pavgra** [comment]
@wivern , 

1. Why does this screen

- Show each line 2 times?
- Do not allow to differentiate between cohorts? - I would even propose to show only 1 cohort per popup or at least introduce selector and additional column / caption

image

2. Doesn't seem that anything is happening:

cc-explore

**Comment by pavgra** [comment]
@wivern , pay attention, I've pushed some changes to improve UX

**Comment by chrisknoll** [comment]
Could you resolve the conflicts?

**Comment by chrisknoll** [comment]
Sorry, this package-lock.json file is also looking conflicted. I know we just made an update to master where we git-ignore this file now, but it seems like git thinks it's a conflict.

**Comment by pavgra** [comment]
@wivern ,

1. Pls resolve conflicts
2. The issue with Explore button and 2 cohorts is still in place:
image

**Comment by wivern** [comment]
Issue with counts isn't reproduced, probably you didn't update WebAPI from 1078 branch?

**Pull request merged**
