### PR TITLE
Export to CSV in explore view.

### PR DESCRIPTION
**Pull request by chrisknoll**

### CODE REVIEW

**Comment by chrisknoll** [comment]
Ok, I applied the same .less styles that are used elsewhere.

Unfortunately, this seems to be a bot of copy-paste between different .less files. Maybe there's a way to have some of these button layouts shared?

**Comment by pavgra** [comment]
If we'd always use bundler, we could create functions / shared classes in less and import those. But now I think your approach is OK

**Comment by chrisknoll** [comment]
> If we'd always use bundler, we could create functions / shared classes in less and import those. 

I'm not sure a bundler is required for that:

Consider if we had a shared module with several BEMHelper instances in it:

```
define(['BEMHelper'],function(BEMHelper) { 

return {
  chartClasses: new BEMHelper(),
  datatableClasses: new BEMHelper()
}
});
```

Etc, such that instead of having to copy and paste things like button styles or graph axis styles, we can just import the 'sharedClasses' module and reference the instance of the bemhelper (chartClasses vs datatableClasses) to expose the specific styles we need.

**Comment by pavgra** [comment]
http://lesscss.org/features/ -> Section "Import Statements"
\+
http://lesscss.org/features/#mixins-feature

**Pull request merged**
