### PR TITLE
criteria set value was changed 

### PR DESCRIPTION
**Pull request by ssuvorov-fls**
see https://github.com/OHDSI/WebAPI/issues/1206)

### CODE REVIEW

**Comment by olga-ganina** [comment]
Hi @anthonysena  , dependency is merged so we can proceed with this one

**Comment by anthonysena** [comment]
This one is a bit complicated so let me detail out what needs to happen with this PR (and its dependencies):

- [x] SkeletonCohortCharacterization is incremented to 1.1.0 (https://github.com/OHDSI/SkeletonCohortCharacterization/pull/17) 
- [ ] SkeletonCohortCharacterization.jar v1.1.0-SNAPSHOT is published to the OHDSI Nexus repo (tagging @leeevans for assistance per my email)
- [ ] The branch `issue-1206-change_criteria_set_fa_type` on SkeletonCohortCharacterization should be updated to reflect the new component version (v1.1.0-SNAPSHOT) by merging in master to that branch. Here is the reference PR: https://github.com/OHDSI/SkeletonCohortCharacterization/pull/15. From there we can review this as part of the WebAPI changes.
- [ ] The changes to WebAPI per this PR: https://github.com/OHDSI/WebAPI/pull/1356 need to be re-issued. I can't restore the PR so we'll need to rebase this work off master and push the branch again (or make a new branch if easier). As part of these changes, we should increment the reference to the SkeletonCohortCharacterization (v1.1.0-SNAPSHOT) in the pom.xml so that we're using the latest release of that component. 
- [ ] Review the changes in this PR as part of the set of changes mentioned above

Tagging @ssuvorov-fls @wivern for comments - maybe there is an easier way to proceed here so feel free to suggest a different path if you don't agree with the above checklist.

**Comment by ssuvorov-fls** [comment]
@anthonysena Hello, please review my pr (https://github.com/OHDSI/SkeletonCohortCharacterization/pull/15), so i can move to fourth item

**Comment by anthonysena** [comment]
Hi @ssuvorov-fls - thanks for taking care of the merge. For the 2nd item above (getting things published into the OHDSI Nexus repo), we're still facing a challenge. In tracing through some of the build issues with @leeevans we discovered that we cannot build the ArachneCommons dependencies and have logged an issue for it: https://github.com/OHDSI/ArachneCommons/issues/225. Once we get that resolved, we should be able to move forward to the 4th item.

**Comment by ssuvorov-fls** [comment]
@anthonysena number 4 is done

**Pull request merged**
