### PR TITLE
Fixed varImp type for Random forest settings

### PR DESCRIPTION
**Pull request by mpozhidaeva**
Fixes https://github.com/OHDSI/Atlas/issues/1168

### CODE REVIEW

**Comment by mpozhidaeva** [comment]
It seems, should be merged into https://github.com/OHDSI/Atlas/pull/1220. Sorry, I didn't notice "parent" issue with the global refactoring of plp/ple.

**Comment by anthonysena** [comment]
Hi @mpozhidaeva - I'm planning to address this issue once I finish up #1220. Since there will be significant changes in that section of the code base, let me put this on hold until those changes are approved an in master and then I can take a look to see what modifications this PR may need. Thanks!

**Comment by mpozhidaeva** [comment]
@anthonysena - sure, thanks a lot

**Comment by anthonysena** [comment]
Hi @mpozhidaeva - would you mind merging in the latest changes in master into this branch now that #1220 is closed? I can then do a review and we can merge in this work. Thanks!

**Comment by anthonysena** [comment]
Closing this out to take the approach as described in https://github.com/OHDSI/Atlas/issues/1168#issuecomment-464180772

**Pull request closed without merging**
