### PR TITLE
Payer plan period criteria

### PR DESCRIPTION
**Pull request by raomane**
Related to https://github.com/OHDSI/circe-be/pull/11
https://github.com/OHDSI/CommonDataModel/issues/120
https://github.com/OHDSI/WebAPI/issues/217

### CODE REVIEW

**Comment by anthonysena** [comment]
Hi @raomane - thanks for contributing this work and apologies for the delay in providing a review. Part of that delay stems from the fact that this PR introduces new functionality that is designed to work against CDM v5.3 which wasn't officially released until early 2018.

We discussed this work on the [last OHDSI Architecture call ](https://docs.google.com/presentation/d/1m0fJtzQsfogppNjtABUqrVT_MbyDklmDgzmgroDBcIs/edit#slide=id.p) and had a good discussion around how we want to introduce new functionality like this into the platform that targets newer features of the CDM. While there is still more discussion required on how to best handle CDM version changes in the tools long term, we did decide on a short term approach. Our short-term approach will be to add a warning in the Payer Plan Period criteria template informing users that when using this criteria, it will only work against a CDM that is using v5.3 features. 

We'd like to get this work into the upcoming release and do that, we'd kindly ask that you rebase your work off the latest work in the Atlas master branch. Once that is done, can you re-establish this PR? @fdefalco has volunteered to add the warning mentioned above so that we can have this put into the upcoming build.

I'm also going to link this PR with a discussion that @chrisknoll started on the Circe repo as it is directly related: https://github.com/OHDSI/circe-be/issues/27. 

Tagging @gowthamrao for awareness as well. 

Please reach out if you have any questions or concerns.

**Comment by gowthamrao** [comment]
tagging @pavgra and Greg

**Comment by chrisknoll** [comment]
Hi, I can manage adding the 2 features: payer plan period criteria and censor windows into 1 PR.  I'll submit a new PR once it's ready (give me a few hours) and I'll close these others out once they become redundant.

**Comment by chrisknoll** [comment]
Covered in #569

**Pull request closed without merging**
