### PR TITLE
Make visibility.core.js AMD compatable.

### PR DESCRIPTION
**Pull request by chrisknoll**
Removed visibility.core from package.json in order to change the implementation.

### CODE REVIEW

**Comment by chrisknoll** [comment]
Btw, in order to clean out old package reference to visibility.js, you will need to run `npm install` again.

**Comment by chrisknoll** [comment]
Sounds complicated.  Who is going to own the repo?  Who's going to publish our fork to NPM?  This is just a short term solution, I'll be submitting a PR to the upstream repo, and I figure it will take them a few weeks to notice it, maybe accept it, and then we can go back to using the NPM managed lib.

But, if you think it's worth the extra hassle, go ahead and we'll update our package.json to the new library.

**Comment by chrisknoll** [comment]
I've opened a PR here https://github.com/ai/visibilityjs/pull/48 but initial feedback does not sound too promising.  Fingers crossed!

**Comment by anthonysena** [comment]
@chrisknoll - thanks for putting this together and from my review & testing, it is working well in both bundled and non-bundled mode. 

I'm hopeful that the folks that manage the visibilityjs repo will include these changes thus making it less code for us to manage as a community. If not, perhaps we can fork the repo as @pavgra into an OHDSI repo for this specific module? Seems like overkill but then perhaps it can be managed in a similar fashion to the atlas charting library?

**Comment by chrisknoll** [comment]
Update, the visibilityjs maintainers, in their infinite wisdom, have decided to reject the PR since it does not follow the model that they deem 'the best':

> This is why I prefer to not add AMD to force any AMD user to migrate to good builders with the latest practices.

So, we'll have to work from a fork (tho, after that experience, I'd rather we drop this library completely on principle).  I'm going to publish the library with AMD support under the `@ohdsi` namespace and will modify the PR to point to the correct version.

**Comment by chrisknoll** [comment]
@anthonysena , i've pushed a forked version of the library to include AMD support. If you have already pulled this branch, you might need to delete your local branch before you pull again (otherwise strange merges may happen). Sorry, i was just keeping the PR commits clean.

**Comment by chrisknoll** [comment]
I made the update in my fork here: https://github.com/chrisknoll/visibilityjs.  The package.json file that was published to npm refrences my fork (not the origional).

**Comment by chrisknoll** [comment]
@pavgra , please approve or dismiss your review. Then we can merge it in. Thanks!

**Pull request merged**
