### PR TITLE
PLP code generation fix

### PR DESCRIPTION
**Pull request by pavgra**
Closes https://github.com/OHDSI/Atlas/issues/740

### CODE REVIEW

**Comment by chrisknoll** [comment]
Sorry: I forget that when we reviewed the PLP script, was the version of the PLP library that is referenced in the script up to date as well? Should we update both the parameters as well as the referenced library are pointing to the latest version?  If it was already set, then disregard.

**Comment by pavgra** [comment]
@chrisknoll , the latest released version fails at Redshift, so I would either wait for the next release or use latest commit instead

**Comment by chrisknoll** [comment]
Of course, let's not update it if it's broken. I hope they know about the redshift issue.

Thanks for checking.

**Comment by pavgra** [comment]
@cgreich , the issue was fixed, but there were no releases after the fix was introduced. So the only option is to replace the `ref = "2.0.0"` with commit hash

**Comment by chrisknoll** [comment]
So, I don't recommend referencing a hash, so we can either wait for an official 2,0.5 or 2.1.0 of PLP or we can just push this PR as is and come back to update it later.

@jreps: do you know if there will be a release of PatientLevelPrediction soon?

**Comment by pavgra** [comment]
@chrisknoll , I'd push it and then update the version as soon as the release happens

**Comment by chrisknoll** [comment]
Ok sounds good to me. Go ahead and we'll revisit this when PLP gets updated.

**Pull request merged**
