### PR TITLE
Permission system improvements 

### PR DESCRIPTION
**Pull request by mpozhidaeva**
Issue: https://github.com/OHDSI/WebAPI/issues/283

### CODE REVIEW

**Comment by chrisknoll** [comment]
Hi, could you sync your fork or rebase your branch to resolve conflicts and resubmit the PR?

**Comment by mpozhidaeva** [comment]
Hello, I updated the branch but don't see any conflicts as before

**Comment by chrisknoll** [comment]
Ok, got it, the rebase showed some kind of conflict, but 'squash and merge' works.  So we should test the pr and then use the 'squash and merge' option to remove the extra commits from master branch commit history.

**Comment by mpozhidaeva** [comment]
Ok, sure

**Comment by anthonysena** [comment]
Left some comments on OHDSI/WebAPI#288 around this item. Having some trouble getting this branch to function properly, in particular the ability to log in with security. I'm wondering if OHDSI/WebAPI#287 should be combined with OHDSI/WebAPI#288 and OHDSI/Atlas#553 as they all have an impact on security and appear to have some inter dependencies?

**Comment by anthonysena** [comment]
Closing this and tracking our work under #561

**Pull request closed without merging**
