### PR TITLE
Fixes Concept Set reload when new concepts picked from vocabulary

### PR DESCRIPTION
**Pull request by pavgra**
fixes https://github.com/OHDSI/Atlas/issues/1518

### CODE REVIEW

**Comment by anthonysena** [comment]
This fixes the behavior reported in #1518 however it breaks in a different scenario. Do all of the steps in #1518 - then, select one of the concept's descendants. Switch to the Included Concepts tab and select one of the concepts to include it in the concept set. The display then disappears. The concept is added to the concept set and then you need to switch to the Concept Set Expression and back to the Included Concept tabs for it to re-load. Before this change, the concept is properly added to the concept set and the display remained intact.

**Comment by pavgra** [comment]
@anthonysena , requests are duplicated now (when you first time switch to the Included Concepts tab)
image

**Comment by anthonysena** [comment]
I'm going to push this to 2.7.1 and explain why in #1518 to keep the bug & troubleshooting together.

**Comment by chrisknoll** [comment]
Be aware I am also looking at issues related to datatables, may want to reference my changes in #1582.

**Comment by anthonysena** [comment]
Sounds good @chrisknoll - the other noteworthy item here is related to the changes underway in #1590. I think once those are in master, we can circle back on this PR - I recall from working with @pavgra on this item that part of the challenge (for me at least) is that there were functions firing in Model.js and in the downstream components and it was fairly difficult to coordinate them all since they were in different places. Let us know if you think it is sensible to wait for you to finish #1582 and then also incorporate those changes here.

**Comment by anthonysena** [comment]
@pavgra - coming back to this item and looked deeper into the behavior you noted earlier (that there were multiple calls to resolve included concepts). What appears to happen is that there is a redundant call the first time we try to find the included concepts - what I noticed is that one call will pass an empty concept set and then finally sends up the current concept set. However, subsequent calls are not repeated even when the concept set definition is changed.

When I contrast this behavior to https://github.com/OHDSI/Atlas/pull/1546/commits/0e6c6b62505532f15e7a80f5084ad2049f64d86b#diff-37aeda83c046a4ff6731a45a79b2cfabR352, the subscription is done at the global level. The result is that any changes to an active concept set then make a call to resolve it which adds a lot of extra, unnecessary traffic to the server.

As discussed between us and @chrisknoll, the ideal solution is to decompose and decouple the concept set services/components so that these actions are controlled by the containing page vs having these handlers at the global application level. I won't attempt these changes in this PR we should aim to do this for 2.8.

From my side, this PR is good to go and addresses the issue in #1518. Let me know if you have any further concerns.

**Pull request merged**
